# Generated by Django 4.1.1 on 2023-01-14 15:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aliances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliance',
            name='member',
            field=models.ManyToManyField(related_name='member', to=settings.AUTH_USER_MODEL),
        ),
    ]
