# Generated by Django 4.1.1 on 2023-01-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', '남성'), ('female', '여성'), ('unknown', '알수없음')], max_length=20),
        ),
        migrations.AddField(
            model_name='hero',
            name='language',
            field=models.CharField(blank=True, choices=[('kr', '한국어'), ('en', 'English')], max_length=10),
        ),
        migrations.AddField(
            model_name='hero',
            name='profileImage',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='hero',
            name='race',
            field=models.CharField(blank=True, choices=[('human', '인간'), ('inhuman', '인휴먼'), ('mutant', '뮤턴트'), ('alien', '외계인'), ('unknown', '알수없음')], max_length=20),
        ),
        migrations.AlterField(
            model_name='hero',
            name='type',
            field=models.CharField(choices=[('combat', '컴뱃'), ('speed', '스피드'), ('blast', '블래스트'), ('universal', '유니버설')], max_length=20),
        ),
    ]
