# Generated by Django 4.1.1 on 2023-01-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0002_hero_charindex_hero_latestuniform'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='uniformName',
            field=models.CharField(default='', max_length=50),
        ),
    ]
